package MaV;

/**
* MaV/AdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/claire/workspace/CommonMaV/idl/Admin.idl
* Tuesday, May 22, 2007 7:17:57 PM CEST
*/

public final class AdminHolder implements org.omg.CORBA.portable.Streamable
{
  public MaV.Admin value = null;

  public AdminHolder ()
  {
  }

  public AdminHolder (MaV.Admin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MaV.AdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MaV.AdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MaV.AdminHelper.type ();
  }

}
