package MaV;


/**
* MaV/AdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/claire/workspace/CommonMaV/idl/Admin.idl
* Tuesday, May 22, 2007 7:17:57 PM CEST
*/

public interface AdminOperations 
{
  void deleteAdmin (int id);
  boolean verifLogin (String login, String pwd);
  boolean saveAdmin (String login, String pwd);
} // interface AdminOperations
