package MaV;


/**
* MaV/Admin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Admin.idl
* Sunday, May 6, 2007 3:30:49 PM CEST
*/

public interface Admin extends AdminOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Admin
