package MaV;

/**
* MaV/CandidatHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/claire/workspace/CommonMaV/idl/Candidat.idl
* Tuesday, May 22, 2007 7:17:57 PM CEST
*/

public final class CandidatHolder implements org.omg.CORBA.portable.Streamable
{
  public MaV.Candidat value = null;

  public CandidatHolder ()
  {
  }

  public CandidatHolder (MaV.Candidat initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MaV.CandidatHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MaV.CandidatHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MaV.CandidatHelper.type ();
  }

}
