package MaV;


/**
* MaV/CandidatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Candidat.idl
* samedi 9 juin 2007 00 h 57 GMT+01:00
*/

public interface CandidatOperations 
{
  int id ();
  void id (int newId);
  String nom ();
  void nom (String newNom);
  String prenom ();
  void prenom (String newPrenom);
  int age ();
  void age (int newAge);
  String profession ();
  void profession (String newProfession);
  MaV.Mandat[] getMandats ();
  MaV.Mandat createMandat (String titre, String anneeD, String anneeF);
} // interface CandidatOperations
