package MaV;


/**
* MaV/Electeur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Electeur.idl
* jeudi 14 juin 2007 20 h 56 GMT+01:00
*/

public final class Electeur implements org.omg.CORBA.portable.IDLEntity
{
  public int insee = (int)0;
  public String nom = null;
  public String prenom = null;
  public int bureau = (int)0;
  public int code = (int)0;

  public Electeur ()
  {
  } // ctor

  public Electeur (int _insee, String _nom, String _prenom, int _bureau, int _code)
  {
    insee = _insee;
    nom = _nom;
    prenom = _prenom;
    bureau = _bureau;
    code = _code;
  } // ctor

} // class Electeur
