package MaV;


/**
* MaV/lcHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Candidat.idl
* samedi 9 juin 2007 09 h 43 GMT+01:00
*/

abstract public class lcHelper
{
  private static String  _id = "IDL:MaV/lc:1.0";

  public static void insert (org.omg.CORBA.Any a, MaV.Candidat[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MaV.Candidat[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = MaV.CandidatHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (MaV.lcHelper.id (), "lc", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MaV.Candidat[] read (org.omg.CORBA.portable.InputStream istream)
  {
    MaV.Candidat value[] = null;
    int _len0 = istream.read_long ();
    value = new MaV.Candidat[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = MaV.CandidatHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MaV.Candidat[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      MaV.CandidatHelper.write (ostream, value[_i0]);
  }

}
