package MaV;


/**
* MaV/ListeC.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Candidat.idl
* Tuesday, April 17, 2007 1:46:47 PM CEST
*/

public interface ListeC extends ListeCOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ListeC
