package MaV;


/**
* MaV/ListeCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Candidat.idl
* Tuesday, April 17, 2007 1:46:47 PM CEST
*/

public interface ListeCOperations 
{
  MaV.Candidat[] getAllCandidats ();
  int getNbVotes (int id);
  MaV.Mandat[] getMandats (int id);
  int addCandidat (MaV.Candidat c);
} // interface ListeCOperations
