package MaV;


/**
* MaV/ListeCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/claire/workspace/CommonMaV/idl/Candidat.idl
* Tuesday, May 22, 2007 7:17:57 PM CEST
*/

public interface ListeCOperations 
{
  MaV.Candidat[] getAllCandidats ();
  void deleteCandidat (int id);
  MaV.Mandat[] getMandats (int id);
  boolean saveCandidat (MaV.Candidat c);
} // interface ListeCOperations
