package MaV;


/**
* MaV/lmHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Candidat.idl
* Tuesday, April 24, 2007 6:29:49 PM CEST
*/

public final class lmHolder implements org.omg.CORBA.portable.Streamable
{
  public MaV.Mandat value[] = null;

  public lmHolder ()
  {
  }

  public lmHolder (MaV.Mandat[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MaV.lmHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MaV.lmHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MaV.lmHelper.type ();
  }

}
