package MaV;


/**
* MaV/MandatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Candidat.idl
* jeudi 14 juin 2007 20 h 56 GMT+01:00
*/

public interface MandatOperations 
{
  int id ();
  void id (int newId);
  String titre ();
  void titre (String newTitre);
  String anneeD ();
  void anneeD (String newAnneeD);
  String anneeF ();
  void anneeF (String newAnneeF);
  void saveMandat ();
} // interface MandatOperations
