package MaV;


/**
* MaV/Mandat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Candidat.idl
* samedi 9 juin 2007 00 h 57 GMT+01:00
*/

public final class Mandat implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String titre = null;
  public String anneeD = null;
  public String anneeF = null;

  public Mandat ()
  {
  } // ctor

  public Mandat (int _id, String _titre, String _anneeD, String _anneeF)
  {
    id = _id;
    titre = _titre;
    anneeD = _anneeD;
    anneeF = _anneeF;
  } // ctor

} // class Mandat
