package MaV;


/**
* MaV/StatsCallBack.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Statistiques.idl
* jeudi 14 juin 2007 20 h 56 GMT+01:00
*/

public interface StatsCallBack extends StatsCallBackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StatsCallBack
