package MaV;


/**
* MaV/StatsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Stats.idl
* Tuesday, April 24, 2007 6:29:44 PM CEST
*/

public interface StatsOperations 
{
  int getNbVotes (int id);
  int getNbVotesParBureau (int idB, int id);
  int getNbVotesParCanton (int idCa, int id);
  int getNbVotesParCirc (int idCi, int id);
  int getNbVotesParDept (int idD, int id);
} // interface StatsOperations
