package MaV;


/**
* MaV/Stats.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/claire/workspace/CommonMaV/idl/Stats.idl
* Tuesday, May 22, 2007 7:17:57 PM CEST
*/

public interface Stats extends StatsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Stats
