package MaV;

/**
* MaV/StatsCallBackHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Statistiques.idl
* jeudi 14 juin 2007 20 h 56 GMT+01:00
*/

public final class StatsCallBackHolder implements org.omg.CORBA.portable.Streamable
{
  public MaV.StatsCallBack value = null;

  public StatsCallBackHolder ()
  {
  }

  public StatsCallBackHolder (MaV.StatsCallBack initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MaV.StatsCallBackHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MaV.StatsCallBackHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MaV.StatsCallBackHelper.type ();
  }

}
