package MaV;


/**
* MaV/Votant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Electeur.idl
* jeudi 14 juin 2007 20 h 56 GMT+01:00
*/

public interface Votant extends VotantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Votant
