package MaV;


/**
* MaV/Votant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Electeur.idl
* Tuesday, April 24, 2007 6:29:56 PM CEST
*/

public interface Votant extends VotantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Votant
