package MaV;


/**
* MaV/VoteCallBackHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Electeur.idl
* samedi 9 juin 2007 00 h 57 GMT+01:00
*/

abstract public class VoteCallBackHelper
{
  private static String  _id = "IDL:MaV/VoteCallBack:1.0";

  public static void insert (org.omg.CORBA.Any a, MaV.VoteCallBack that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MaV.VoteCallBack extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MaV.VoteCallBackHelper.id (), "VoteCallBack");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MaV.VoteCallBack read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_VoteCallBackStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MaV.VoteCallBack value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static MaV.VoteCallBack narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MaV.VoteCallBack)
      return (MaV.VoteCallBack)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MaV._VoteCallBackStub stub = new MaV._VoteCallBackStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static MaV.VoteCallBack unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MaV.VoteCallBack)
      return (MaV.VoteCallBack)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MaV._VoteCallBackStub stub = new MaV._VoteCallBackStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
