

module MaV {
    interface Candidat{
			attribute unsigned long id;
			attribute string nom;
			attribute string prenom;
			attribute unsigned long age;
			attribute string profession;
			string toString();
	};
	
	struct Mandat{
		unsigned long id;
		string titre;
		string anneeD;
		string anneeF;
	};
	
	typedef sequence<Candidat> lc;
	typedef sequence<Mandat> lm;
	
    interface ListeC {
    	lc getAllCandidats();
    	void deleteCandidat(in unsigned long id);
    	lm getMandats(in unsigned long id);
    	boolean saveCandidat(in Candidat c);
    };
    
   
};

