module MaV {

    struct Electeur {
		unsigned long insee;
		string nom;
		string prenom;
		unsigned long bureau;
		unsigned long code;
    };
    
      
    interface Votant{
    	//Permet de tester son bureau de vote, et ses infos
    	Electeur verifierElecteur(in unsigned long insee, in unsigned long code);
    	boolean exists(in unsigned long insee, in unsigned long code);
    	boolean aDejaVote(in unsigned long insee);
		void votePour2(in unsigned long id, in unsigned long insee, in unsigned long idBureau);
		void votePour(in unsigned long id, in unsigned long insee, in unsigned long idBureau);
		void deleteElecteur(in unsigned long id);
    	boolean saveElecteur(in Electeur e);
    };
    
    
};
