module MaV {
	
	 struct Stats {
			unsigned long idCandidat;
			unsigned long idBureau;
			unsigned long nbVotes;
		};

	
	typedef sequence<Stats> lstats;
	
	interface StatsCallBack{
		
		void callback(in lstats s);
	};
	
	
	interface Statistiques {
		void enregistrerClientsStats(in StatsCallBack obj);
		
		void deleteClientsStats(in StatsCallBack obj);

       	unsigned long getNbVotes(in unsigned long id);
    	unsigned long getNbVotesParBureau(in unsigned long idB, in unsigned long id);
    	unsigned long getNbVotesParCanton(in unsigned long idCa, in unsigned long id);
    	unsigned long getNbVotesParCirc(in unsigned long idCi, in unsigned long id);
    	unsigned long getNbVotesParDept(in unsigned long idD, in unsigned long id);
    };
    
};