package MaV;


/**
* MaV/_AdminImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/claire/workspace/CommonMaV/idl/Admin.idl
* Tuesday, May 22, 2007 7:17:55 PM CEST
*/

public abstract class _AdminImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements MaV.Admin, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _AdminImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("deleteAdmin", new java.lang.Integer (0));
    _methods.put ("verifLogin", new java.lang.Integer (1));
    _methods.put ("saveAdmin", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MaV/Admin/deleteAdmin
       {
         int id = in.read_ulong ();
         this.deleteAdmin (id);
         out = $rh.createReply();
         break;
       }

       case 1:  // MaV/Admin/verifLogin
       {
         String login = in.read_string ();
         String pwd = in.read_string ();
         boolean $result = false;
         $result = this.verifLogin (login, pwd);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // MaV/Admin/saveAdmin
       {
         String login = in.read_string ();
         String pwd = in.read_string ();
         boolean $result = false;
         $result = this.saveAdmin (login, pwd);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MaV/Admin:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _AdminImplBase
