package MaV;


/**
* MaV/_CandidatImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/claire/workspace/CommonMaV/idl/Candidat.idl
* Tuesday, May 22, 2007 7:17:56 PM CEST
*/

public abstract class _CandidatImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements MaV.Candidat, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _CandidatImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_id", new java.lang.Integer (0));
    _methods.put ("_set_id", new java.lang.Integer (1));
    _methods.put ("_get_nom", new java.lang.Integer (2));
    _methods.put ("_set_nom", new java.lang.Integer (3));
    _methods.put ("_get_prenom", new java.lang.Integer (4));
    _methods.put ("_set_prenom", new java.lang.Integer (5));
    _methods.put ("_get_age", new java.lang.Integer (6));
    _methods.put ("_set_age", new java.lang.Integer (7));
    _methods.put ("_get_profession", new java.lang.Integer (8));
    _methods.put ("_set_profession", new java.lang.Integer (9));
    _methods.put ("toString", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MaV/Candidat/_get_id
       {
         int $result = (int)0;
         $result = this.id ();
         out = $rh.createReply();
         out.write_ulong ($result);
         break;
       }

       case 1:  // MaV/Candidat/_set_id
       {
         int newId = in.read_ulong ();
         this.id (newId);
         out = $rh.createReply();
         break;
       }

       case 2:  // MaV/Candidat/_get_nom
       {
         String $result = null;
         $result = this.nom ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // MaV/Candidat/_set_nom
       {
         String newNom = in.read_string ();
         this.nom (newNom);
         out = $rh.createReply();
         break;
       }

       case 4:  // MaV/Candidat/_get_prenom
       {
         String $result = null;
         $result = this.prenom ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // MaV/Candidat/_set_prenom
       {
         String newPrenom = in.read_string ();
         this.prenom (newPrenom);
         out = $rh.createReply();
         break;
       }

       case 6:  // MaV/Candidat/_get_age
       {
         int $result = (int)0;
         $result = this.age ();
         out = $rh.createReply();
         out.write_ulong ($result);
         break;
       }

       case 7:  // MaV/Candidat/_set_age
       {
         int newAge = in.read_ulong ();
         this.age (newAge);
         out = $rh.createReply();
         break;
       }

       case 8:  // MaV/Candidat/_get_profession
       {
         String $result = null;
         $result = this.profession ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // MaV/Candidat/_set_profession
       {
         String newProfession = in.read_string ();
         this.profession (newProfession);
         out = $rh.createReply();
         break;
       }

       case 10:  // MaV/Candidat/_toString
       {
         String $result = null;
         $result = this._toString ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MaV/Candidat:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _CandidatImplBase
