package MaV;


/**
* MaV/_ListeCImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Candidat.idl
* jeudi 14 juin 2007 20 h 41 GMT+01:00
*/

public abstract class _ListeCImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements MaV.ListeC, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ListeCImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getAllCandidats", new java.lang.Integer (0));
    _methods.put ("deleteCandidat", new java.lang.Integer (1));
    _methods.put ("saveCandidat", new java.lang.Integer (2));
    _methods.put ("createCandidat", new java.lang.Integer (3));
    _methods.put ("getNomCandidat", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MaV/ListeC/getAllCandidats
       {
         MaV.Candidat $result[] = null;
         $result = this.getAllCandidats ();
         out = $rh.createReply();
         MaV.lcHelper.write (out, $result);
         break;
       }

       case 1:  // MaV/ListeC/deleteCandidat
       {
         int id = in.read_ulong ();
         this.deleteCandidat (id);
         out = $rh.createReply();
         break;
       }

       case 2:  // MaV/ListeC/saveCandidat
       {
         MaV.Candidat c = MaV.CandidatHelper.read (in);
         boolean $result = false;
         $result = this.saveCandidat (c);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // MaV/ListeC/createCandidat
       {
         String nom = in.read_string ();
         String prenom = in.read_string ();
         int age = in.read_ulong ();
         String profession = in.read_string ();
         MaV.Candidat $result = null;
         $result = this.createCandidat (nom, prenom, age, profession);
         out = $rh.createReply();
         MaV.CandidatHelper.write (out, $result);
         break;
       }

       case 4:  // MaV/ListeC/getNomCandidat
       {
         int idCandidat = in.read_ulong ();
         String $result = null;
         $result = this.getNomCandidat (idCandidat);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MaV/ListeC:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ListeCImplBase
