package MaV;


/**
* MaV/_MandatImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Candidat.idl
* jeudi 14 juin 2007 20 h 41 GMT+01:00
*/

public abstract class _MandatImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements MaV.Mandat, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _MandatImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_id", new java.lang.Integer (0));
    _methods.put ("_set_id", new java.lang.Integer (1));
    _methods.put ("_get_titre", new java.lang.Integer (2));
    _methods.put ("_set_titre", new java.lang.Integer (3));
    _methods.put ("_get_anneeD", new java.lang.Integer (4));
    _methods.put ("_set_anneeD", new java.lang.Integer (5));
    _methods.put ("_get_anneeF", new java.lang.Integer (6));
    _methods.put ("_set_anneeF", new java.lang.Integer (7));
    _methods.put ("saveMandat", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MaV/Mandat/_get_id
       {
         int $result = (int)0;
         $result = this.id ();
         out = $rh.createReply();
         out.write_ulong ($result);
         break;
       }

       case 1:  // MaV/Mandat/_set_id
       {
         int newId = in.read_ulong ();
         this.id (newId);
         out = $rh.createReply();
         break;
       }

       case 2:  // MaV/Mandat/_get_titre
       {
         String $result = null;
         $result = this.titre ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // MaV/Mandat/_set_titre
       {
         String newTitre = in.read_string ();
         this.titre (newTitre);
         out = $rh.createReply();
         break;
       }

       case 4:  // MaV/Mandat/_get_anneeD
       {
         String $result = null;
         $result = this.anneeD ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // MaV/Mandat/_set_anneeD
       {
         String newAnneeD = in.read_string ();
         this.anneeD (newAnneeD);
         out = $rh.createReply();
         break;
       }

       case 6:  // MaV/Mandat/_get_anneeF
       {
         String $result = null;
         $result = this.anneeF ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // MaV/Mandat/_set_anneeF
       {
         String newAnneeF = in.read_string ();
         this.anneeF (newAnneeF);
         out = $rh.createReply();
         break;
       }

       case 8:  // MaV/Mandat/saveMandat
       {
         this.saveMandat ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MaV/Mandat:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _MandatImplBase
