package MaV;


/**
* MaV/_StatistiquesImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Statistiques.idl
* jeudi 14 juin 2007 20 h 41 GMT+01:00
*/

public abstract class _StatistiquesImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements MaV.Statistiques, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _StatistiquesImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("enregistrerClientsStats", new java.lang.Integer (0));
    _methods.put ("deleteClientsStats", new java.lang.Integer (1));
    _methods.put ("getNbVotes", new java.lang.Integer (2));
    _methods.put ("getNbVotesParBureau", new java.lang.Integer (3));
    _methods.put ("getNbVotesParCanton", new java.lang.Integer (4));
    _methods.put ("getNbVotesParCirc", new java.lang.Integer (5));
    _methods.put ("getNbVotesParDept", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MaV/Statistiques/enregistrerClientsStats
       {
         MaV.StatsCallBack obj = MaV.StatsCallBackHelper.read (in);
         this.enregistrerClientsStats (obj);
         out = $rh.createReply();
         break;
       }

       case 1:  // MaV/Statistiques/deleteClientsStats
       {
         MaV.StatsCallBack obj = MaV.StatsCallBackHelper.read (in);
         this.deleteClientsStats (obj);
         out = $rh.createReply();
         break;
       }

       case 2:  // MaV/Statistiques/getNbVotes
       {
         int id = in.read_ulong ();
         int $result = (int)0;
         $result = this.getNbVotes (id);
         out = $rh.createReply();
         out.write_ulong ($result);
         break;
       }

       case 3:  // MaV/Statistiques/getNbVotesParBureau
       {
         int idB = in.read_ulong ();
         int id = in.read_ulong ();
         int $result = (int)0;
         $result = this.getNbVotesParBureau (idB, id);
         out = $rh.createReply();
         out.write_ulong ($result);
         break;
       }

       case 4:  // MaV/Statistiques/getNbVotesParCanton
       {
         int idCa = in.read_ulong ();
         int id = in.read_ulong ();
         int $result = (int)0;
         $result = this.getNbVotesParCanton (idCa, id);
         out = $rh.createReply();
         out.write_ulong ($result);
         break;
       }

       case 5:  // MaV/Statistiques/getNbVotesParCirc
       {
         int idCi = in.read_ulong ();
         int id = in.read_ulong ();
         int $result = (int)0;
         $result = this.getNbVotesParCirc (idCi, id);
         out = $rh.createReply();
         out.write_ulong ($result);
         break;
       }

       case 6:  // MaV/Statistiques/getNbVotesParDept
       {
         int idD = in.read_ulong ();
         int id = in.read_ulong ();
         int $result = (int)0;
         $result = this.getNbVotesParDept (idD, id);
         out = $rh.createReply();
         out.write_ulong ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MaV/Statistiques:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _StatistiquesImplBase
