package MaV;


/**
* MaV/_StatsImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Stats.idl
* Tuesday, April 24, 2007 6:29:22 PM CEST
*/

public abstract class _StatsImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements MaV.Stats, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _StatsImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getNbVotes", new java.lang.Integer (0));
    _methods.put ("getNbVotesParBureau", new java.lang.Integer (1));
    _methods.put ("getNbVotesParCanton", new java.lang.Integer (2));
    _methods.put ("getNbVotesParCirc", new java.lang.Integer (3));
    _methods.put ("getNbVotesParDept", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MaV/Stats/getNbVotes
       {
         int id = in.read_ulong ();
         int $result = (int)0;
         $result = this.getNbVotes (id);
         out = $rh.createReply();
         out.write_ulong ($result);
         break;
       }

       case 1:  // MaV/Stats/getNbVotesParBureau
       {
         int idB = in.read_ulong ();
         int id = in.read_ulong ();
         int $result = (int)0;
         $result = this.getNbVotesParBureau (idB, id);
         out = $rh.createReply();
         out.write_ulong ($result);
         break;
       }

       case 2:  // MaV/Stats/getNbVotesParCanton
       {
         int idCa = in.read_ulong ();
         int id = in.read_ulong ();
         int $result = (int)0;
         $result = this.getNbVotesParCanton (idCa, id);
         out = $rh.createReply();
         out.write_ulong ($result);
         break;
       }

       case 3:  // MaV/Stats/getNbVotesParCirc
       {
         int idCi = in.read_ulong ();
         int id = in.read_ulong ();
         int $result = (int)0;
         $result = this.getNbVotesParCirc (idCi, id);
         out = $rh.createReply();
         out.write_ulong ($result);
         break;
       }

       case 4:  // MaV/Stats/getNbVotesParDept
       {
         int idD = in.read_ulong ();
         int id = in.read_ulong ();
         int $result = (int)0;
         $result = this.getNbVotesParDept (idD, id);
         out = $rh.createReply();
         out.write_ulong ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MaV/Stats:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _StatsImplBase
