package MaV;


/**
* MaV/_VoteCallBackImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Electeur.idl
* samedi 9 juin 2007 09 h 37 GMT+01:00
*/

public abstract class _VoteCallBackImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements MaV.VoteCallBack, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _VoteCallBackImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("callback", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MaV/VoteCallBack/callback
       {
         MaV.Stats s[] = MaV.lstatsHelper.read (in);
         this.callback (s);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MaV/VoteCallBack:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _VoteCallBackImplBase
