package MaV;


/**
* MaV/Admin_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Admin.idl
* jeudi 14 juin 2007 20 h 41 GMT+01:00
*/

public class Admin_Tie extends _AdminImplBase
{

  // Constructors
  public Admin_Tie ()
  {
  }

  public Admin_Tie (MaV.AdminOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void deleteAdmin (int id)
  {
    _impl.deleteAdmin(id);
  } // deleteAdmin

  public boolean verifLogin (String login, String pwd)
  {
    return _impl.verifLogin(login, pwd);
  } // verifLogin

  public boolean saveAdmin (String login, String pwd)
  {
    return _impl.saveAdmin(login, pwd);
  } // saveAdmin

  private MaV.AdminOperations _impl;

} // class Admin_Tie
