package MaV;


/**
* MaV/Admin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/claire/workspace/CommonMaV/idl/Admin.idl
* Tuesday, May 22, 2007 7:17:55 PM CEST
*/

public interface Admin extends AdminOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Admin
