package MaV;


/**
* MaV/Candidat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Candidat.idl
* Tuesday, April 24, 2007 6:29:33 PM CEST
*/

public final class Candidat implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String nom = null;
  public String prenom = null;
  public int age = (int)0;
  public String profession = null;

  public Candidat ()
  {
  } // ctor

  public Candidat (int _id, String _nom, String _prenom, int _age, String _profession)
  {
    id = _id;
    nom = _nom;
    prenom = _prenom;
    age = _age;
    profession = _profession;
  } // ctor

} // class Candidat
