package MaV;


/**
* MaV/CandidatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/claire/workspace/CommonMaV/idl/Candidat.idl
* Tuesday, May 22, 2007 7:17:56 PM CEST
*/

public interface CandidatOperations 
{
  int id ();
  void id (int newId);
  String nom ();
  void nom (String newNom);
  String prenom ();
  void prenom (String newPrenom);
  int age ();
  void age (int newAge);
  String profession ();
  void profession (String newProfession);
  String _toString ();
} // interface CandidatOperations
