package MaV;


/**
* MaV/ListeC_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Candidat.idl
* Tuesday, April 17, 2007 1:47:27 PM CEST
*/

public class ListeC_Tie extends _ListeCImplBase
{

  // Constructors
  public ListeC_Tie ()
  {
  }

  public ListeC_Tie (MaV.ListeCOperations impl)
  {
    super ();
    _impl = impl;
  }

  public MaV.Candidat[] getAllCandidats ()
  {
    return _impl.getAllCandidats();
  } // getAllCandidats

  public int getNbVotes (int id)
  {
    return _impl.getNbVotes(id);
  } // getNbVotes

  public MaV.Mandat[] getMandats (int id)
  {
    return _impl.getMandats(id);
  } // getMandats

  public int addCandidat (MaV.Candidat c)
  {
    return _impl.addCandidat(c);
  } // addCandidat

  private MaV.ListeCOperations _impl;

} // class ListeC_Tie
