package MaV;


/**
* MaV/ListeC.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/claire/workspace/CommonMaV/idl/Candidat.idl
* Tuesday, May 22, 2007 7:17:56 PM CEST
*/

public interface ListeC extends ListeCOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ListeC
