package MaV;


/**
* MaV/ListeC.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Candidat.idl
* Sunday, May 6, 2007 3:18:20 PM CEST
*/

public interface ListeC extends ListeCOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ListeC
