package MaV;


/**
* MaV/ListeCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Candidat.idl
* jeudi 14 juin 2007 20 h 41 GMT+01:00
*/

public interface ListeCOperations 
{
  MaV.Candidat[] getAllCandidats ();
  void deleteCandidat (int id);
  boolean saveCandidat (MaV.Candidat c);
  MaV.Candidat createCandidat (String nom, String prenom, int age, String profession);
  String getNomCandidat (int idCandidat);
} // interface ListeCOperations
