package MaV;


/**
* MaV/ListeCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Candidat.idl
* Sunday, May 6, 2007 3:18:20 PM CEST
*/

public interface ListeCOperations 
{
  MaV.Candidat[] getAllCandidats ();
  void deleteCandidat (int id);
  MaV.Mandat[] getMandats (int id);
  boolean saveCandidat (MaV.Candidat c);
} // interface ListeCOperations
