package MaV;


/**
* MaV/ListeC_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Candidat.idl
* jeudi 14 juin 2007 20 h 41 GMT+01:00
*/

public class ListeC_Tie extends _ListeCImplBase
{

  // Constructors
  public ListeC_Tie ()
  {
  }

  public ListeC_Tie (MaV.ListeCOperations impl)
  {
    super ();
    _impl = impl;
  }

  public MaV.Candidat[] getAllCandidats ()
  {
    return _impl.getAllCandidats();
  } // getAllCandidats

  public void deleteCandidat (int id)
  {
    _impl.deleteCandidat(id);
  } // deleteCandidat

  public boolean saveCandidat (MaV.Candidat c)
  {
    return _impl.saveCandidat(c);
  } // saveCandidat

  public MaV.Candidat createCandidat (String nom, String prenom, int age, String profession)
  {
    return _impl.createCandidat(nom, prenom, age, profession);
  } // createCandidat

  public String getNomCandidat (int idCandidat)
  {
    return _impl.getNomCandidat(idCandidat);
  } // getNomCandidat

  private MaV.ListeCOperations _impl;

} // class ListeC_Tie
