package MaV;


/**
* MaV/lmHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Candidat.idl
* jeudi 14 juin 2007 20 h 41 GMT+01:00
*/

public final class lmHolder implements org.omg.CORBA.portable.Streamable
{
  public MaV.Mandat value[] = null;

  public lmHolder ()
  {
  }

  public lmHolder (MaV.Mandat[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MaV.lmHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MaV.lmHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MaV.lmHelper.type ();
  }

}
