package MaV;


/**
* MaV/Mandat_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Candidat.idl
* jeudi 14 juin 2007 20 h 41 GMT+01:00
*/

public class Mandat_Tie extends _MandatImplBase
{

  // Constructors
  public Mandat_Tie ()
  {
  }

  public Mandat_Tie (MaV.MandatOperations impl)
  {
    super ();
    _impl = impl;
  }

  public int id ()
  {
    return _impl.id();
  } // id
  public void id (int newId)
  {
    _impl.id(newId);
  } // id

  public String titre ()
  {
    return _impl.titre();
  } // titre
  public void titre (String newTitre)
  {
    _impl.titre(newTitre);
  } // titre

  public String anneeD ()
  {
    return _impl.anneeD();
  } // anneeD
  public void anneeD (String newAnneeD)
  {
    _impl.anneeD(newAnneeD);
  } // anneeD

  public String anneeF ()
  {
    return _impl.anneeF();
  } // anneeF
  public void anneeF (String newAnneeF)
  {
    _impl.anneeF(newAnneeF);
  } // anneeF

  public void saveMandat ()
  {
    _impl.saveMandat();
  } // saveMandat

  private MaV.MandatOperations _impl;

} // class Mandat_Tie
