package MaV;

/**
* MaV/MandatHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Candidat.idl
* jeudi 14 juin 2007 20 h 41 GMT+01:00
*/

public final class MandatHolder implements org.omg.CORBA.portable.Streamable
{
  public MaV.Mandat value = null;

  public MandatHolder ()
  {
  }

  public MandatHolder (MaV.Mandat initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MaV.MandatHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MaV.MandatHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MaV.MandatHelper.type ();
  }

}
