package MaV;


/**
* MaV/Mandat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Candidat.idl
* Tuesday, April 17, 2007 1:47:27 PM CEST
*/

public final class Mandat implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String titre = null;
  public String annee = null;

  public Mandat ()
  {
  } // ctor

  public Mandat (int _id, String _titre, String _annee)
  {
    id = _id;
    titre = _titre;
    annee = _annee;
  } // ctor

} // class Mandat
