package MaV;


/**
* MaV/StatistiquesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Statistiques.idl
* samedi 9 juin 2007 09 h 37 GMT+01:00
*/

public interface StatistiquesOperations 
{
  int getNbVotes (int id);
  int getNbVotesParBureau (int idB, int id);
  int getNbVotesParCanton (int idCa, int id);
  int getNbVotesParCirc (int idCi, int id);
  int getNbVotesParDept (int idD, int id);
} // interface StatistiquesOperations
