package MaV;


/**
* MaV/Stats.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Electeur.idl
* samedi 9 juin 2007 09 h 37 GMT+01:00
*/

public final class Stats implements org.omg.CORBA.portable.IDLEntity
{
  public int idCandidat = (int)0;
  public int idBureau = (int)0;
  public int nbVotes = (int)0;

  public Stats ()
  {
  } // ctor

  public Stats (int _idCandidat, int _idBureau, int _nbVotes)
  {
    idCandidat = _idCandidat;
    idBureau = _idBureau;
    nbVotes = _nbVotes;
  } // ctor

} // class Stats
