package MaV;


/**
* MaV/Stats.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Stats.idl
* Sunday, May 6, 2007 3:33:12 PM CEST
*/

public interface Stats extends StatsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Stats
