package MaV;


/**
* MaV/StatsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Stats.idl
* Sunday, May 6, 2007 3:33:12 PM CEST
*/

public interface StatsOperations 
{
  int getNbVotes (int id);
  int getNbVotesParBureau (int idB, int id);
  int getNbVotesParCanton (int idCa, int id);
  int getNbVotesParCirc (int idCi, int id);
  int getNbVotesParDept (int idD, int id);
} // interface StatsOperations
