package MaV;


/**
* MaV/StatistiquesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Statistiques.idl
* jeudi 14 juin 2007 20 h 41 GMT+01:00
*/

public interface StatistiquesOperations 
{
  void enregistrerClientsStats (MaV.StatsCallBack obj);
  void deleteClientsStats (MaV.StatsCallBack obj);
  int getNbVotes (int id);
  int getNbVotesParBureau (int idB, int id);
  int getNbVotesParCanton (int idCa, int id);
  int getNbVotesParCirc (int idCi, int id);
  int getNbVotesParDept (int idD, int id);
} // interface StatistiquesOperations
