package MaV;


/**
* MaV/StatsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/claire/workspace/CommonMaV/idl/Stats.idl
* Tuesday, May 22, 2007 7:17:56 PM CEST
*/

public interface StatsOperations 
{
  int getNbVotes (int id);
  int getNbVotesParBureau (int idB, int id);
  int getNbVotesParCanton (int idCa, int id);
  int getNbVotesParCirc (int idCi, int id);
  int getNbVotesParDept (int idD, int id);
} // interface StatsOperations
