package MaV;


/**
* MaV/Stats.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Stats.idl
* Tuesday, April 24, 2007 6:29:22 PM CEST
*/

public interface Stats extends StatsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Stats
