package MaV;


/**
* MaV/StatsCallBack_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Statistiques.idl
* jeudi 14 juin 2007 20 h 41 GMT+01:00
*/

public class StatsCallBack_Tie extends _StatsCallBackImplBase
{

  // Constructors
  public StatsCallBack_Tie ()
  {
  }

  public StatsCallBack_Tie (MaV.StatsCallBackOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void callback (MaV.Stats[] s)
  {
    _impl.callback(s);
  } // callback

  private MaV.StatsCallBackOperations _impl;

} // class StatsCallBack_Tie
