package MaV;

/**
* MaV/StatsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Stats.idl
* Sunday, May 6, 2007 3:33:12 PM CEST
*/

public final class StatsHolder implements org.omg.CORBA.portable.Streamable
{
  public MaV.Stats value = null;

  public StatsHolder ()
  {
  }

  public StatsHolder (MaV.Stats initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MaV.StatsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MaV.StatsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MaV.StatsHelper.type ();
  }

}
