package MaV;


/**
* MaV/VotantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Electeur.idl
* jeudi 14 juin 2007 20 h 41 GMT+01:00
*/

public interface VotantOperations 
{

  //Permet de tester son bureau de vote, et ses infos
  MaV.Electeur verifierElecteur (int insee, int code);
  boolean exists (int insee, int code);
  boolean aDejaVote (int insee);
  void votePour2 (int id, int insee, int idBureau);
  void votePour (int id, int insee, int idBureau);
  void deleteElecteur (int id);
  boolean saveElecteur (MaV.Electeur e);
} // interface VotantOperations
