package MaV;


/**
* MaV/Votant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Electeur.idl
* Sunday, May 6, 2007 3:58:23 PM CEST
*/

public interface Votant extends VotantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Votant
