package MaV;


/**
* MaV/Votant_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Electeur.idl
* samedi 9 juin 2007 09 h 37 GMT+01:00
*/

public class Votant_Tie extends _VotantImplBase
{

  // Constructors
  public Votant_Tie ()
  {
  }

  public Votant_Tie (MaV.VotantOperations impl)
  {
    super ();
    _impl = impl;
  }


  //Permet de tester son bureau de vote, et ses infos
  public MaV.Electeur verifierElecteur (int insee, int code)
  {
    return _impl.verifierElecteur(insee, code);
  } // verifierElecteur

  public boolean exists (int insee, int code)
  {
    return _impl.exists(insee, code);
  } // exists

  public boolean aDejaVote (int insee)
  {
    return _impl.aDejaVote(insee);
  } // aDejaVote

  public void votePour2 (int id, int insee, MaV.VoteCallBack objCallBack)
  {
    _impl.votePour2(id, insee, objCallBack);
  } // votePour2

  public void votePour (int id, int insee, int idBureau)
  {
    _impl.votePour(id, insee, idBureau);
  } // votePour

  public void deleteElecteur (int id)
  {
    _impl.deleteElecteur(id);
  } // deleteElecteur

  public boolean saveElecteur (MaV.Electeur e)
  {
    return _impl.saveElecteur(e);
  } // saveElecteur

  private MaV.VotantOperations _impl;

} // class Votant_Tie
