package MaV;


/**
* MaV/VoteCallBack_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Electeur.idl
* samedi 9 juin 2007 09 h 37 GMT+01:00
*/

public class VoteCallBack_Tie extends _VoteCallBackImplBase
{

  // Constructors
  public VoteCallBack_Tie ()
  {
  }

  public VoteCallBack_Tie (MaV.VoteCallBackOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void callback (MaV.Stats[] s)
  {
    _impl.callback(s);
  } // callback

  private MaV.VoteCallBackOperations _impl;

} // class VoteCallBack_Tie
