package MaV;


/**
* MaV/VoteCallBackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/nephos/cours/iup/m1/cvs/CommonMaV/idl/Electeur.idl
* samedi 9 juin 2007 09 h 37 GMT+01:00
*/

public interface VoteCallBackOperations 
{
  void callback (MaV.Stats[] s);
} // interface VoteCallBackOperations
